apiVersion: v1
kind: Namespace
metadata:
  name: ag-grid
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: ag-grid
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: ag-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru"]
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 2.5Gi
            requests:
              memory: 500Mi
